### ISSUE TITLE
Redirect VS Build Step Error Messages

### ISSUE THREAD

**Issue by VKaczmarek** [menees/MegaBuild#1]
Is there a possibility to redirect detailed build error messages from VS Build Step?

**Comment by menees** [comment]
The VS step already has a "Redirect Console Streams To Output Window" checkbox. Make sure that's checked on your VS step. The VS step also allows you to pass in custom args to DevEnv, but that's all I can support for VS command line automation.

[Microsoft recommends](https://docs.microsoft.com/en-us/visualstudio/ide/reference/devenv-command-line-switches) using MSBuild instead of DevEnv for command line builds, and I do too. I no longer use MegaBuild's VS step anywhere (at home or work) because Microsoft has broken (and later fixed) the DevEnv command line builds multiple times with VS2015 and VS2019.

To switch to MSBuild, you'll need to configure a step for each solution configuration you want to build (e.g., one with Configuration=Debug and one with Configuration=Release). But MSBuild gives you the flexibility to specify many other settings including property overrides, detailed verbosity, etc.
